// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: customer_auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAuthRecord = `-- name: CreateAuthRecord :one
INSERT INTO customer_auth ("id", "is_verified", "opt", "channel", "customer_id")
VALUES ($1, $2, $3, $4, $5) RETURNING "id"
`

type CreateAuthRecordParams struct {
	ID         uuid.UUID `json:"id"`
	IsVerified bool      `json:"is_verified"`
	Opt        string    `json:"opt"`
	Channel    string    `json:"channel"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) CreateAuthRecord(ctx context.Context, arg CreateAuthRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAuthRecord,
		arg.ID,
		arg.IsVerified,
		arg.Opt,
		arg.Channel,
		arg.CustomerID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAuthRecordByCustomerId = `-- name: GetAuthRecordByCustomerId :one
SELECT id, customer_id, is_verified, opt, channel, created_at FROM customer_auth
WHERE customer_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetAuthRecordByCustomerId(ctx context.Context, customerID uuid.UUID) (CustomerAuth, error) {
	row := q.db.QueryRowContext(ctx, getAuthRecordByCustomerId, customerID)
	var i CustomerAuth
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IsVerified,
		&i.Opt,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthRecordHistory = `-- name: GetAuthRecordHistory :many
SELECT id, customer_id, is_verified, opt, channel, created_at FROM customer_auth
WHERE customer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAuthRecordHistory(ctx context.Context, customerID uuid.UUID) ([]CustomerAuth, error) {
	rows, err := q.db.QueryContext(ctx, getAuthRecordHistory, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerAuth{}
	for rows.Next() {
		var i CustomerAuth
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IsVerified,
			&i.Opt,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastRecord = `-- name: GetLastRecord :one
SELECT id, customer_id, is_verified, opt, channel, created_at FROM customer_auth
WHERE customer_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastRecord(ctx context.Context, customerID uuid.UUID) (CustomerAuth, error) {
	row := q.db.QueryRowContext(ctx, getLastRecord, customerID)
	var i CustomerAuth
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IsVerified,
		&i.Opt,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}
