// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCredential(ctx context.Context, arg AddCredentialParams) (uuid.UUID, error)
	CreateAuthRecord(ctx context.Context, arg CreateAuthRecordParams) (uuid.UUID, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (uuid.UUID, error)
	CreateShowStrategy(ctx context.Context, arg CreateShowStrategyParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	GetAuthRecordByCustomerId(ctx context.Context, customerID uuid.UUID) (CustomerAuth, error)
	GetAuthRecordHistory(ctx context.Context, customerID uuid.UUID) ([]CustomerAuth, error)
	GetCredentialsByCustomerId(ctx context.Context, customerID uuid.UUID) ([]Credential, error)
	GetCustomerById(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByUserName(ctx context.Context, userName string) (Customer, error)
	GetLastRecord(ctx context.Context, customerID uuid.UUID) (CustomerAuth, error)
	GetShowStrategy(ctx context.Context, credentialID uuid.UUID) (ShowStrategy, error)
	GetUserByCustomerName(ctx context.Context, id uuid.UUID) (GetUserByCustomerNameRow, error)
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateShowStrategy(ctx context.Context, arg UpdateShowStrategyParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UserCredentials(ctx context.Context, customerID uuid.UUID) ([]UserCredentialsRow, error)
	VerifyCustomerOpt(ctx context.Context, isVerified bool) error
}

var _ Querier = (*Queries)(nil)
