// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCredential(ctx context.Context, arg AddCredentialParams) (uuid.UUID, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (uuid.UUID, error)
	CreateShowStrategy(ctx context.Context, arg CreateShowStrategyParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	GetCredentialsByCustomerId(ctx context.Context, customerID uuid.UUID) ([]Credential, error)
	GetCustomerById(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByUserName(ctx context.Context, userName string) (Customer, error)
	GetShowStrategy(ctx context.Context, credentialID uuid.UUID) (ShowStrategy, error)
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateShowStrategy(ctx context.Context, arg UpdateShowStrategyParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
